model:
  name: "logistic_regression"
  input_dim: 6

data:
  dataset: "real"          
  npz_path: "data/preprocessed/cleaned_x_y_hot.npz"
  batch_size: 2048
  seed: 42
  normalize_x: true
  x_norm_method: "minmax"
  normalize_y: true
  y_norm_method: "minmax"
  return_stats: true
  val_ratio: 0.2

optim:
  name: "adam"
  lr: 0.008  
  weight_decay: 0.00001

train:
  num_epochs: 100
  log_interval: 5
  device: "cuda"  # auto

logging:
  root_dir: "./runs"
  experiment_name: "real_dataset_experiment"

checkpoint:
  save_best: true
  save_last: false
  monitor: "val_loss"
  mode: "min"


cv:
  n_splits: 5           # 1 means no CV, just a single train/val split
  shuffle: true
  seed: 42
